HideoKojima/urls.py
from django.contrib import admin
from django.urls import re_path, include
# from ../hello import views

urlpatterns = [
    re_path('', include("hello.urls_hello")),
    re_path('admin/', admin.site.urls, name='admin_url'),
    re_path("hello/", include("hello.urls_hello")),
    re_path("video/", include("hello.urls_hello")),
]

hello/models.py
from django.db import models
# from datetime import datetime
from django.contrib.auth import get_user_model
from django.urls import reverse


User = get_user_model()


class Video(models.Model):
    class Meta():
        db_table = "Video"
        # ordering = ['-Video_data']

    Video_url = models.URLField()
    Video_name = models.CharField(max_length=200)
    Video_description = models.TextField()
    Video_data = models.DateTimeField(auto_now_add=True)
    # Video_data = models.DateTimeField(default = datetime.now, blank = True)
    Video_likes = models.IntegerField(default=0)
    Video_dislikes = models.IntegerField(default=0)

    def __str__(self):
        return self.Video_name

    def get_absolute_url(self):
        return reverse('one_video_url', args=[self.id])


class Comment(models.Model):
    class Meta():
        db_table = "Comment"
        ordering = ['-Comment_data']

    Comment_text = models.TextField(verbose_name="New comment")
    Comment_data = models.DateTimeField(auto_now_add=True)
    # Comment_data = models.DateTimeField(default=datetime.now, blank=True)
    Comment_Video = models.ForeignKey(Video, on_delete=models.CASCADE)
    Comment_User = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Comment_text

# Create your models here.

hello/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Video, Comment
from django.contrib.auth.models import User
from . import form
from django.template.context_processors import csrf
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def hello(request):
    return HttpResponse("!!!HELLO!!!")


def names(request):
    return render(
        request,
        'mytemplate.html',
        {"name": "PETR", "lastname": "PETROV"}
    )


def ShowAll(request):
    content = []  # [[vid, [все коментарии]], [vid, [все коментарии]],
    # [vid, [все коментарии]]]
    for vid in Video.objects.all():
        oneVid = [vid]
        comments_ = Comment.objects.filter(Comment_Video_id=vid.id)
        # [video, [(comment, name),(comment, name),(comment, name)]
        # oneVid.append(comments_)
        list_name = []
        for com in comments_:
            list_name.append(User.objects.get(id=com.Comment_User.id))
        comments_names = list(zip(comments_, list_name))
        oneVid.append(comments_names)
        content.append(oneVid)

    # пагинация страниц
    pagination = Paginator(content, 2)
    page_number = request.GET.get('page', 1)
    page = pagination.get_page(page_number)

    other_pages = page.has_other_pages()

    if page.has_previous():
        previous_url = '?page={}'.format(page.previous_page_number())
    else:
        previous_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        "content": page,
        "other_pages": other_pages,
        "previous_url": previous_url,
        "next_url": next_url
    }

    return render(request, "AllVideos1.html", context=context)


def Search(request, *args, **kwargs):
    search_query = request.GET.get('search')
    found = Video.objects.filter(Q(Video_name__icontains=search_query))

    context = {
        "found": found,
        "args": args,
        "kwargs": kwargs
    }

    return render(request, "Search.html", context=context)


def OneVideo(request, video_id):
    # print(request.user.id)
    args = {}
    comment_form = form.CommentsForm
    args.update(csrf(request))
    args["form"] = comment_form
    args["video"] = Video.objects.get(id=video_id)
    args["Comment"] = Comment.objects.filter(Comment_Video_id=video_id)
    return render(request, "OneVideo.html", args)


def LikeaJax(request):
    if request.GET:
        idvideo = request.GET['addlike']
        video = Video.objects.get(id=idvideo)
        video.Video_likes += 1
        video.save()
    return HttpResponse(video.Video_likes)


def DisLikeaJax(request):
    print("1111")
    if request.GET:
        idvideo = request.GET['adddislike']
        video = Video.objects.get(id=idvideo)
        video.Video_dislikes += 1
        video.save()
    print("1111")
    return HttpResponse(video.Video_dislikes)


def AddComment(request, video_id):
    if request.POST:
        forma = form.CommentsForm(request.POST)
        if forma.is_valid():
            comment = forma.save(commit=False)
            comment.Comment_Video = Video.objects.get(id=video_id)
            comment.Comment_User = User.objects.get(id=request.user.id)
            forma.save()
    return redirect("/video/get/" + str(video_id) + "/")


def Registration(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user = authenticate(
                username=new_user_form.cleaned_data['username'],
                password=new_user_form.cleaned_data['password2']
            )
            login(request, new_user)
            return redirect("/video/all/")
        else:
            args["form"] = new_user_form
            args["errorlist"] = "The two password fields didn't match"
    return render(request, "Registration.html", args)


def Login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/video/all/")
        else:
            args["login_error"] = "User not found"
            return render(request, "Login.html", args)
    else:
        return render(request, "Login.html", args)


def Logout(request):
    logout(request)
    return redirect('video_all_url')


# Create your views here.

hello/templates/AllVideos.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}
{% block AllVideos %}

{% for cont in content %}
<iframe width="958" height="539" src={{ cont.0.Video_url }} frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>

<a href="/video/get/{{ cont.0.id }}/"><h1>{{ cont.0.Video_name }} </h1></a>
<h3>{{ cont.0.Video_description }} </h3>
<h3>{{ cont.0.Video_data }} </h3>

<img src="{% static 'like.png' %}" width="100" class="like" name="{{ cont.o.id }}"> LIKES:
<h3 id="{{ con.0.id }}"> {{ cont.0.Video_likes }} </h3>
<hr>

<!--<a href="/video/addlike/{{ cont.o.id }}"></a>-->

{% for com in cont.1 %}
<h2>{{ com.0.Comment_text }}</h2>
<h2>{{ com.0.Comment_data }}</h2>
<h2>{{ com.1 }}</h2>
{% endfor %}

{% endfor %}

{% endblock %}

hello/templates/AllVideos1.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}
{% block AllVideos1 %}


<div class="container-fluid text-center">
    {% for cont in content.object_list %}

    <iframe width="800" height="500" src={{ cont.0.Video_url }} frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
</iframe>
<div>
<a href="/video/get/{{ cont.0.id }}/">
    <p id="video_name">{{ cont.0.Video_name }} </p>
</a>
</div>
<p style="font-size: large">
    <a style="font-weight: bold">Description:   </a>{{ cont.0.Video_description }}
</p>

<a style="font-weight: bold">Date:   </a>
<a style="font-size: small">{{ cont.0.Video_data }}</a>
<!-- <p class="fx">
<img src="{% static 'like.png' %}" width="30" class="like" name="{{ cont.o.id }}" align="middle">
<code style="color: black">Likes:</code> {{ cont.0.Video_likes }}</p>
<hr> -->
<br>
{% endfor %}
</div>
<!-- <hr> -->
<br>

{% if other_pages %}
<nav aria-label="..." class="nav justify-content-center">
    <ul class="pagination">
        <li class="page-item {% if not previous_url %} disabled {% endif %}">
            <a class="page-link" href="{{ previous_url }}" tabindex="-1">Previous</a>
        </li>

        {% for n in content.paginator.page_range %}

        {% if content.number == n %}

        <li class="page-item active">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
        </li>

        {% elif n > content.number|add:-3 and n < content.number|add:3 %}

        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>

        {% endif %}

        {% endfor %}

        <li class="page-item {% if not next_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_url }}" tabindex="-1">Next</a>
        </li>
    </ul>
</nav>
{% endif %}

{% endblock %}

hello/templates/Login.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}

{% block Log %}

<form action="{% url 'login_url' %}" method="post" id="logform">
    {% csrf_token %}
    <p>
        <input type="text" name="username" id="username" placeholder="User name" required="">
    </p>
    <p>
        <input type="password" name="password" id="password" placeholder="Password" required="">
    </p>

    <input class="btn btn-outline-dark" type="submit" value="Enter">

    {% if login_error %}
    <p>
        <label class="error">{{ login_error }}</label>
    </p>
    {% endif %}
</form>

{% endblock %}

hello/templates/MainTemplate.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<nav class="navbar navbar-expand-lg navbar-light bg-none">
  <a class="navbar-brand" href="">Additive technology
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
  aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon">
  </span>
</button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
  <div class="navbar-nav">

    <a class="nav-item nav-link btn" style="color: #000080" href="{% url 'video_all_url' %}">
      <i class="fab fa-youtube"></i>Video
    </a>

    <a class="nav-item nav-link btn" style="color: black" onclick="openNewWin('https://www.linkedin.com/in/alehcharnets/')">
      <i class="fab fa-linkedin"></i>About the author
    </a>

    {% if not user.is_authenticated %}
    <a class="nav-item nav-link btn" style="color: #004d00" href="{% url 'registration_url' %}">
      <i class="fas fa-user-plus"></i>Registration
    </a>
    {% endif %}

    {% if not user.is_authenticated %}
    <a class="nav-item nav-link btn" style="color: green" href="{% url 'login_url' %}">
      <i class="fas fa-sign-in-alt"></i>Log in
    </a>
    {% endif %}

    {% if user.is_authenticated %}
    <a class="nav-item nav-link btn" style="color: red" href="{% url 'logout_url' %}">
      <i class="fas fa-sign-out-alt"></i>Log out
    </a>
    {% endif %}

    {% if user.is_authenticated and user.is_staff %}
    <a class="nav-item nav-link btn" style="color: #999900" href="/admin/">
      <i class="fas fa-tools"></i>Admin
    </a>
    {% endif %}

  </div>
</div>
<form class="form-inline" action="{% url 'search_url' %}"><i class="fas fa-video"></i>
  <input class="form-control mr-sm-2" type="search" placeholder="Video search" aria-label="Search" name="search" required="">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i>Search</button>
</form>
</nav>


<head>
    <meta charset="utf-8">
    <title>TECH</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<!--     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> -->
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> -->

    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

<!-- Для иконок -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>



<body>
<br><br>

{% block Video %}       {% endblock %}
{% block AllVideos1 %}  {% endblock %}
{% block OneVideo %}    {% endblock %}
{% block Search %}      {% endblock %}
{% block Log %}         {% endblock %}
{% block Reg %}         {% endblock %}

</body>
</html>

hello/templates/OneVideo.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}
{% block OneVideo %}


<div class="container-fluid text-center">

    <iframe width="800" height="500" src={{ video.Video_url }} frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>

<div style="padding: 20px">
    <p class="fx">
        <a href="#" id="like" name="{{ video.id }}">
            <span class="fas fa-heart">
            </span>
        </a>
        <span id="count_likes">{{ video.Video_likes }}</span>

        <a href="#" id="dislike" name="{{ video.id }}">
            <span class="fas fa-thumbs-down">
            </span>
        </a>
        <span id="count_dislikes">{{ video.Video_dislikes }}</span>
    </p>
</div>

<div style="padding: 30px">
    <p style="font-size: xx-large; font-weight: bold;">{{ video.Video_name }}</p>
    <p style="font-size: large">
        <a style="font-weight: bold">Description:   </a> {{ video.Video_description }}
    </p>
</div>

<div class="container text-center">
    <a class="fx"><font size="6" color="#666633" face="Comic Sans MS"> Comments ( {{ Comment|length }} ) : </font></a>
<br>
        {% for com in Comment %}
    <div class="container text-center" id="comment_text">
        <h5>{{ com.Comment_text }}</h5>
        <a style="font-weight: bold">Date:   </a><a>{{ com.Comment_data }}</a>
        <a style="font-weight: bold">User:   </a><a>{{ com.Comment_User }}</a>
    </div>
        {% endfor %}
</div>
</div>

{% if not user.is_authenticated %}
<div class="block1">
    <a>To leave a comment
        <a href="{% url 'registration_url' %}">register
        </a> or
        <a href="{% url 'login_url' %}">login
        </a>
    </a>
</div>
{% endif %}

{% if user.is_authenticated %}
<form action="/video/addcomment/{{ video.id }}/" method="post">
    {% csrf_token %}
    <h5>
        <label for="id_Comment_text">New comment:</label>
    </h5>
    <p>
        <textarea name="Comment_text" cols="60" rows="10" id="id_Comment_text" required></textarea>
    </p>
    <p>
        <input class="btn btn-outline-dark" type="submit" value="Add comment">
    </p>
</form>
{% endif %}

{% endblock %}

hello/templates/Registration.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}

{% block Reg %}
<br><br><br>

<form action="{% url 'registration_url' %}" method="post" id="regform2">
    {% csrf_token %}

    <p>
<!-- <label for="id_username">Username:
</label> -->
<input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="Username">
<span class="helptext">
</span>
<ul>
    <li>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    </li>
</ul>
</p>
<p>
<!-- <label for="id_password1">Password:
</label> -->
<input type="password" name="password1" required="" id="id_password1" placeholder="Password">
<span class="helptext">
</span>
</p>
<ul>
    <li>Your password can't be too similar to your other personal information.
    </li>
    <li>Your password must contain at least 8 characters.
    </li>
    <li>Your password can't be a commonly used password.
    </li>
    <li>Your password can't be entirely numeric.
    </li>
</ul>
<p>
<!-- <label for="id_password2">Password confirmation:
</label> -->
<input type="password" name="password2" required="" id="id_password2" placeholder="Password confirmation">
<span class="helptext">
</span>
<ul>
    <li>Enter the same password as before, for verification.
    </li>
</ul>
</p>


<p>
    <input class="btn btn-outline-dark" type="submit" value="Registration">
</p>
{% if errorlist %}
<p>
    <label class="error">{{ errorlist }}</label>
</p>
{% endif %}

</form>

{% endblock %}

hello/templates/Search.html
{% extends 'MainTemplate.html' %}
{% load staticfiles %}

{% block Search %}

<div class="container-fluid text-center">

    <h3 id="video_serch">Video found: {{ found.count }} </h3>

    {% for video in found %}
    <h4 id="video_name">
        <a href="{{ video.get_absolute_url }}" style="text-decoration: none">{{ video.Video_name }}
        </a>
    </h4>
    {% endfor %}

</div>

{% endblock %}

hello/templates/mytemplate.html
{% extends 'MainTemplate.html' %}

{% block Video %}

<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-xl-12 col-sm-6 col-md-4">
            <i></i>

            <h3>{{ name }}</h3>
            <p>{{ lastname }}</p>

        </div>
        <div class="col-xl-12 col-sm-6 col-md-4">

            <h3>{{ name }}</h3>
            <p>{{ lastname }}</p>

        </div>
            <div class="col-xl-12 col-sm-6 col-md-4">

            <h3>{{ name }}</h3>
            <p>{{ lastname }}</p>

        </div>
            <div class="col-xl-12 col-sm-6 col-md-4">

            <h3>{{ name }}</h3>
            <p>{{ lastname }}</p>

        </div>
    </div>
</div>

{% endblock %}